config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "lists#index"
  resources :lists, only: [:index, :show, :new, :create] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity, notice: 'Bookmark could not be created'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity, notice: 'List could not be created'
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, bookmark] do |f| %>
  <%= f.input :movie_id, collection: Movie.all %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="navbar-lewagon">
      <%= link_to lists_path do %>
      <%= image_tag "movie.png", width: 60 %>
      <% end %>
      <h1>LUCAS' THEATER</h1>
      <%= link_to new_list_path do %>
      <%= image_tag "create-list.png", width: 60 %>
      <% end %>
    </div>
        <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list do |f| %>
  <%= f.input :name %>
  <%= f.submit "Create" %>
<% end %>

app/views/lists/index.html.erb
<div class="cards">
  <% @lists.each do |list| %>
    <%= link_to list_path(list) do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(images.jpeg)">
        <%= list.name %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/lists/new.html.erb
<h1>Creating a new watchlist</h1>

<%= render 'form', list:@list %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<% @bookmarks.each do |bookmark| %>
    <p>There are <%= @bookmarks.count %> bookmarks in this list</p>
    <p><%= bookmark.movie.rating %>/5 - <%= bookmark.movie.title %></p>
    <p><%= bookmark.movie.overview %></p>
    <%= image_tag bookmark.movie.poster_url, alt: "movie-poster", width: 200 %>
      <br>
    <p>User comment: <%= bookmark.comment %></p>
      <br>
    <p><%= button_to "Remove this bookmark from my list", bookmark_path(bookmark), method: :delete %></p>
<% end %>
<br>
<p><%= render 'bookmarks/form', list:@list, bookmark:@bookmark %></p>